### ISSUE TITLE
[BUG] Issues when using mysqlclient==2.2.0

### ISSUE THREAD

**Issue by jake-skipper** [rackspace/runway#1939]
### Bug Description

`mysqlclient`'s bump to `2.2.0` has broken unit tests as it now does a `pkg-config` looking for a MySQL or MariaDB client library. We were unable to find one that is easily installable in the SAM build-python3.9 image. We've temporarily pinned `mysqlclient` back to restore functionality, but this is something that will need to be tackled eventually.

### Expected Behavior

`mysqlclient` should install via `pip` without issues during unit testing.

### Steps To Reproduce

1. `docker run --rm -it public.ecr.aws/sam/build-python3.9:latest /bin/bash`,
2. `pip install mysqlclient==2.2.0`.

### Runway version

Not Runway version dependent, this is an upstream dependency of Runway.

### Installation Type

pypi (pip, pipenv, poetry, etc)

### OS / Environment

public.ecr.aws/sam/build-python3.9:latest image, which is used in Runway unit tests.

### Anything else?

This is a fresh issue affecting a lot of people based on Google search results, and the `mysqlclient` devs seem to be pointing users towards distro maintainers, etc for a fix for the missing (or unavailable) mysql/mariadb client libs. I suggest we pin this back to get things operational, and let this simmer a bit. Hopefully by the time we need to truly tackle this one a better solution will be available (or we can regroup to remove Runway's `mysqlclient` dependency).

**Comment by mbordash2** [comment]
This is not a priority at this time and has no impact on the tool functionality.  So long as this version of mysqlclient is pinned this shouldn't be an issue.
