### ISSUE TITLE
[BUG] .Trash directory growing to large sizes with repeated terraform work

### ISSUE THREAD

**Issue by jake-skipper** [rackspace/runway#1952]
### Bug Description

On repeated executions involving Terraform deployments, Runway's repeated removal of Terraform files into `.Trash` can cause large amounts of disk usage.

### Expected Behavior

Running `plan` repeatedly shouldn't end up generating gigs of disk usage that isn't apparent to the end user. If `.Trash` functionality is needed, it should be configured in such a way as to not cause excessive use and be more apparent to end user what is happening.

### Steps To Reproduce

Repeatedly `runway plan` against a Terraform module and take note of the `.Trash` directory.

### Runway version

2.6.6

### Installation Type

pypi (pip, pipenv, poetry, etc)

### OS / Environment

N/A

### Anything else?

N/A

**Comment by mbordash2** [comment]
Removal of `.send2trash` should address this issue reported.
