### ISSUE TITLE
improve auth@edge error handling

### ISSUE THREAD

**Issue by edgarpoce** [rackspace/runway#456]
Parameter existence check is executed after attempt to parse. I suggest to the parsing after the validation in order to provide the client a better error message

https://github.com/onicagroup/runway/blob/2b4274df5b7aa177180eb90cc8ae7a4c8f1c65ca/runway/hooks/staticsite/auth_at_edge/templates/parse_auth/__init__.py#L49

**Comment by mbordash2** [comment]
Staticsite auth capabilities to be removed.
